NAMES = ["bart", "homer", "marge", "lisa"]
WARNING = "# Generated by create-proxies script.\n\n"
# Generate docker-compose.yml.
#
with open("docker-compose.yml", "w") as f:
    f.write(WARNING)
    f.write("version: '3'\n\nservices:\n")
    f.write(
        """  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next-pwr
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
"""
    )
    for index, name in enumerate(NAMES):
        f.write(f"  tor-{name}:\n")
        f.write(f"    container_name: 'tor-{name}'\n")
        f.write("    image: 'pickapp/tor-proxy:latest'\n")
        f.write("    ports:\n")
        f.write(f"      - '{9990+index}:8888'\n")
        f.write("    environment:\n")
        f.write("      - IP_CHANGE_SECONDS=60\n")
        f.write("    restart: always\n")

    f.write(
        """volumes:
  db:
    driver: local"""
    )
# Generate proxy-list.txt.
#
with open("proxy-list.txt", "w") as f:
    f.write(WARNING)

    for index, name in enumerate(NAMES):
        f.write(f"http://127.0.0.1:{9990+index}\n")
